<?php

namespace AppBundle\Repository;

/**
 * Usuario2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Usuario2Repository extends \Doctrine\ORM\EntityRepository
{
}
